// Space/Space/src/Views/Details.jsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getUsers } from '../Service/Service';

const Details = () => {
    const { id } = useParams();
    const [users, setUsers] = useState([]);
    const [user, setName] = useState([]);
    const obj = [];

    useEffect(() => {
        if (id)
        {
            const fetchUsers = async () => {
                const users = await getUsers();
                const userId = users.find((user) => user.id === id);
                obj[0] = userId; // Para poder usar map hay que meter el JSON en un array.
                setName(userId.name);
                if (users)
                {
                    setUsers(obj);
                }
                else
                {
                    console.error('Usuario no Encontrado.');
                }
            };
            fetchUsers();
        }
    }, [id]);

    return (
        <div>
            <h1>Usuario de: {user}</h1>
            <ul className='none'>
                {users.map((user, index) => (
                    <li key={index}>{user.name} {user.surname1} {user.email}</li>
                ))}
            </ul>
        </div>
    );
};

export default Details;

// Angular/src/app/Views/Details.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { UsersService } from '../service/users.service';

@Component({
  selector: 'app-details',
  template: `
    <div>
      <h1>Usuario de: {{ user }}</h1>
      <ul class="none">
        <li *ngFor="let user of users">
          {{ user.name }} {{ user.surname1 }} {{ user.email }}
        </li>
      </ul>
    </div>
  `
})
export class DetailsComponent implements OnInit {
  users: any[] = [];
  user: string = '';
  id: string | null = '';

  constructor(private route: ActivatedRoute, private usersService: UsersService) {}

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id) {
      this.fetchUsers();
    }
  }

  async fetchUsers() {
    const users = await this.usersService.getUsers();
    const userId = users.find((user) => user.id === this.id);
    if (userId) {
      this.user = userId.name;
      this.users = [userId]; // Para poder usar *ngFor hay que meter el JSON en un array.
    } else {
      console.error('Usuario no Encontrado.');
    }
  }
}
