// Space/Space/src/Views/Read.jsx
import React, { useEffect, useState } from 'react';
import { getUsers } from '../Service/Service';
import { useNavigate } from 'react-router-dom';
import logo from '../assets/spinner.gif';

const Read = () => {
    const navegar = useNavigate();
    const [users, setUsers] = useState();
    const [isLoading, setIsLoading] = useState(true);

useEffect(() => {
    setIsLoading(true);
    const fetchItems = async () => {
      const users = await getUsers();
      console.log(users);
      setIsLoading(false);
      setUsers(users);
    };
    fetchItems();
  }, []);

  if (isLoading) {
    return <div><h2>Cargando...</h2><img src={logo} alt='Rueda Cargando'></img></div>;
  }

  return (
    <div>
      <h2>Lista de users con Imágenes</h2>
      <br />
      <button onClick={ (e) => navegar('/create')} className='btn btn-success left'>Añadir Usuario</button>
      <br /><br />
      <table>
        <thead>
            <tr><th>ID</th><th>Nombre</th><th>Apellido</th><th>E-mail</th><th>Acciones</th></tr>
        </thead>
        <tbody>
                {users.map((user, i) => (
                    <tr key={i}><td>{user.id}</td><td>{user.name}</td><td>{user.surname1}</td><td>{user.email}</td><td><button onClick={ (e) => navegar(`/details/${user.id}`)} className='btn btn-primary'>Detalles</button>&nbsp;&nbsp;<button onClick={ (e) => navegar(`/create/${user.id}`)} className='btn btn-info'>Actualizar</button>&nbsp;&nbsp;<button onClick={(e)=> navegar(`/delete/${user.id}`)} className='btn btn-danger'>Eliminar</button></td></tr>
                ))}
        </tbody>
      </table>
    </div>
  );
};

export default Read;

// Angular/src/app/Views/Read.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { getUsers } from '../Service/Service';
import logo from '../assets/spinner.gif';

@Component({
  selector: 'app-read',
  templateUrl: './read.component.html',
  styleUrls: ['./read.component.css']
})
export class ReadComponent implements OnInit {
  users: any;
  isLoading = true;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.isLoading = true;
    this.fetchItems();
  }

  async fetchItems() {
    const users = await getUsers();
    console.log(users);
    this.isLoading = false;
    this.users = users;
  }

  navigateToCreate() {
    this.router.navigate(['/create']);
  }

  navigateToDetails(userId: number) {
    this.router.navigate([`/details/${userId}`]);
  }

  navigateToUpdate(userId: number) {
    this.router.navigate([`/create/${userId}`]);
  }

  navigateToDelete(userId: number) {
    this.router.navigate([`/delete/${userId}`]);
  }
}

<!-- read.component.html -->
<div *ngIf="isLoading">
  <h2>Cargando...</h2>
  <img [src]="logo" alt="Rueda Cargando">
</div>
<div *ngIf="!isLoading">
  <h2>Lista de users con Imágenes</h2>
  <br />
  <button (click)="navigateToCreate()" class="btn btn-success left">Añadir Usuario</button>
  <br /><br />
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>E-mail</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let user of users; let i = index">
        <td>{{ user.id }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.surname1 }}</td>
        <td>{{ user.email }}</td>
        <td>
          <button (click)="navigateToDetails(user.id)" class="btn btn-primary">Detalles</button>
          &nbsp;&nbsp;
          <button (click)="navigateToUpdate(user.id)" class="btn btn-info">Actualizar</button>
          &nbsp;&nbsp;
          <button (click)="navigateToDelete(user.id)" class="btn btn-danger">Eliminar</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
